name: Push docker image to docker registry

on:
  push:
    tags:
      - "*"

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}
      - name: docker build
        run: docker build --cache-from kruhlmann/ackchyually:latest -t "kruhlmann/ackchyually:$(shell git describe --tag --always | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')" -t kruhlmann/ackchyually:latest .
      - name: docker push
        run: docker push --all-tags kruhlmann/ackchyually
